/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "MyPdfV1.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(MyPdfV1) 

 MyPdfV1::MyPdfV1(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _mu,
                        RooAbsReal& _sigma) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   mu("mu","mu",this,_mu),
   sigma("sigma","sigma",this,_sigma)
 { 
 } 


 MyPdfV1::MyPdfV1(const MyPdfV1& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   mu("mu",this,other.mu),
   sigma("sigma",this,other.sigma)
 { 
 } 
/* wikipedia
Double_t MyPdfV1::evaluate() const {
  Double_t pi=acos(-1);
  Double_t a=-8*(pi-3)/(3*pi*(pi-4));
  Double_t t1 = (x-mu)/sqrt(2*sigma);
  Double_t t2 = (x+mu)/sqrt(2*sigma);
  
  return 0.5*(sqrt(1-exp(-pow(t1,2)*(4/pi+a*pow(t1,2))/(1+a*pow(t1,2))))+sqrt(1-exp(-pow(t2,2)*(4/pi+a*pow(t2,2))/(1+a*pow(t2,2)))));
*/
  //http://www.hindawi.com/journals/mpe/2012/124029/
  Double_t MyPdfV1::evaluate() const {
  Double_t pi=acos(-1);
  Double_t a=-8*(pi-3)/(3*pi*(pi-4));
  Double_t t1 = (x-mu)/sqrt(2*sigma);
  Double_t t2 = (x+mu)/sqrt(2*sigma);
  return 0.5*(tanh(77*t1/75+116/25*tanh(147*t1/73-76/7*tanh(51*t1/278)))+tanh(77*t2/75+116/25*tanh(147*t2/73-76/7*tanh(51*t2/278))));
 } 



